#!/bin/sh

readonly script_path=`cd ${0%/*} && echo $PWD`
readonly script_name=${0##*/}

pushd "$script_path/../.." >/dev/null

chmod +x bin/json-proxy
node bin/json-proxy -c examples/cli/json-proxy.json --html5mode
